name = "autonovaq"
compatibility_date = "2026-05-28"
compatibility_flags = ["nodejs_compat"]
main = "_worker.js"

[assets]
directory = "out"
binding = "ASSETS"

[observability]
enabled = true
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = true
persist = true
head_sampling_rate = 1
